name: Demo App Android Release

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12"
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"
      - run: flutter doctor -v
      - run: flutter upgrade --force
      - run: flutter pub get
      - run: flutter build apk
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.version.outputs.content }}
          commit: ${{ github.sha }}
