name: Demo App Android Release

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
#       - name: Create a Release in GitHub
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
#           token: ${{ secrets.GH_TOKEN }}
#           tag: ${{ steps.version.outputs.content }}
#           commit: ${{ github.sha }}
